version: '2'

services:
  golang-service:
    image: enkaypeter/golang-gin-sqlite-gorm
    volumes:
        - ./inventory:/go/src/app
    restart: "always"
    ports:
      - 3000:3000

  phpweb-service:
    image: php:5.6-apache
    depends_on:
      - golang-service
    volumes:
      - ./web:/var/www
    ports:
      - 5000:80
